import { useState } from 'react';
import { Archive, Clock, Pencil, RotateCcw, Target } from 'lucide-react';
import { Badge, Empty, Field, FormError, Modal, SearchBox } from '../components/common.jsx';
import { matches } from '../services/utils.js';

export default function Missions({data,onEdit,onArchive,onRestore,busy}) {
  const [search,setSearch]=useState(''); const [status,setStatus]=useState('active'); const [difficulty,setDifficulty]=useState('');
  const filtered=data.misiones.filter(m => (status==='all' || m.activa===(status==='active')) && (!difficulty || m.dificultad===difficulty) && matches(`${m.titulo} ${m.insigniaNombre}`,search));
  return <><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Buscar una misión o insignia"/><div className="toolbar-actions"><select value={status} onChange={e => setStatus(e.target.value)} aria-label="Estado de las misiones"><option value="active">Activas</option><option value="archived">Archivadas</option><option value="all">Todas las misiones</option></select><select value={difficulty} onChange={e => setDifficulty(e.target.value)} aria-label="Dificultad"><option value="">Todas las dificultades</option>{['Baja','Media','Alta'].map(d => <option key={d}>{d}</option>)}</select></div></div><div className="mission-cards">{filtered.map(m => { const point=data.puntos.find(p => p.id===m.puntoInteresId); const completions=data.progreso.filter(p => p.misionId===m.id).length; return <article className={`mission-card ${!m.activa ? 'mission-archived' : ''}`} key={m.id}><div className="mission-card-top"><span className="mission-emoji">{m.insigniaEmoji}</span><Badge tone={!m.activa ? 'neutral' : m.dificultad==='Alta' ? 'rose' : m.dificultad==='Media' ? 'amber' : ''}>{m.activa ? `Dificultad ${m.dificultad.toLowerCase()}` : 'Archivada'}</Badge></div><h2>{m.titulo}</h2><p className="mission-location">{point?.nombre || 'Punto no disponible'}</p><p className="mission-clue">{m.descripcionPista}</p><div className="mission-meta"><span><Target size={14}/> {m.puntos} XP</span><span><Clock size={14}/> {m.tiempoEstimadoMin} min</span></div><div className="mission-award"><span>{m.insigniaEmoji}</span><div><small>INSIGNIA</small><strong>{m.insigniaNombre}</strong></div></div><div className="mission-card-footer"><span>{completions} {completions===1 ? 'logro' : 'logros'}</span><div><button className="icon-button" disabled={busy} aria-label={`Editar ${m.titulo}`} onClick={() => onEdit(m)}><Pencil size={16}/></button>{m.activa ? <button className="icon-button" disabled={busy} aria-label={`Archivar ${m.titulo}`} onClick={() => onArchive(m)}><Archive size={16}/></button> : <button className="icon-button" disabled={busy} aria-label={`Reactivar ${m.titulo}`} onClick={() => onRestore(m)}><RotateCcw size={16}/></button>}</div></div></article>; })}</div>{!filtered.length && <section className="panel"><Empty title="Sin misiones en esta vista" text="Cambia los filtros o crea una nueva misión."/></section>}<p className="result-count">{filtered.length} misiones · El archivo conserva los puntos y el historial de los usuarios.</p></>;
}

export function MissionForm({mission,points,onSave,onClose}) {
  const [form,setForm]=useState(mission || {titulo:'',descripcionPista:'',puntos:30,tiempoEstimadoMin:10,dificultad:'Baja',puntoInteresId:points[0]?.id || '',insigniaNombre:'',insigniaEmoji:'🏅',activa:true});
  const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const set=(key,value) => setForm(f => ({...f,[key]:value}));
  async function submit(e) { e.preventDefault(); setError(''); setSaving(true); try { await onSave({...form,titulo:form.titulo.trim(),descripcionPista:form.descripcionPista.trim(),insigniaNombre:form.insigniaNombre.trim(),insigniaEmoji:form.insigniaEmoji.trim(),puntos:Number(form.puntos),tiempoEstimadoMin:Number(form.tiempoEstimadoMin),puntoInteresId:Number(form.puntoInteresId)}); } catch(e) { setError(e.message); setSaving(false); } }
  return <Modal title={mission ? 'Editar misión' : 'Crear una nueva misión'} onClose={onClose} locked={saving} wide><form onSubmit={submit}><div className="form-grid"><Field label="Título de la misión"><input required minLength={3} maxLength={160} value={form.titulo} onChange={e => set('titulo',e.target.value)} placeholder="Una aventura por descubrir"/></Field><Field label="Punto de interés"><select required value={form.puntoInteresId} onChange={e => set('puntoInteresId',e.target.value)}><option value="">Selecciona un lugar</option>{points.map(p => <option value={p.id} key={p.id}>{p.nombre}</option>)}</select></Field><div className="field-full"><Field label="Descripción y pista"><textarea required minLength={3} maxLength={2000} rows={3} value={form.descripcionPista} onChange={e => set('descripcionPista',e.target.value)} placeholder="Ayuda a los exploradores a llegar a su destino…"/></Field></div><Field label="Puntos otorgados (XP)"><input type="number" min={1} max={10000} step={1} required value={form.puntos} onChange={e => set('puntos',e.target.value)}/></Field><Field label="Tiempo estimado (minutos)"><input type="number" min={1} max={1440} step={1} required value={form.tiempoEstimadoMin} onChange={e => set('tiempoEstimadoMin',e.target.value)}/></Field><Field label="Dificultad"><select value={form.dificultad} onChange={e => set('dificultad',e.target.value)}>{['Baja','Media','Alta'].map(d => <option key={d}>{d}</option>)}</select></Field><Field label="Nombre de la insignia"><input required minLength={2} maxLength={120} value={form.insigniaNombre} onChange={e => set('insigniaNombre',e.target.value)} placeholder="Explorador del campus"/></Field><Field label="Emoji de la insignia"><input required maxLength={16} value={form.insigniaEmoji} onChange={e => set('insigniaEmoji',e.target.value)}/></Field><Field label="Estado"><select value={form.activa ? 'true' : 'false'} onChange={e => set('activa',e.target.value==='true')}><option value="true">Activa</option><option value="false">Archivada</option></select></Field></div><p className="form-note">Los puntos ya obtenidos por los usuarios se conservan al editar una misión.</p><FormError message={error}/><div className="modal-actions"><button type="button" className="secondary-button" disabled={saving} onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving || !points.length}>{saving ? 'Guardando…' : 'Guardar misión'}</button></div></form></Modal>;
}
