import { ArrowRight, Award, Compass, MapPin, Target, Users, TrendingUp } from 'lucide-react';
import { Stat, Empty } from '../components/common.jsx';
import { byPoints, initials, formatDate } from '../services/utils.js';

export default function Overview({data,go,onUser}) {
  const {usuarios,misiones,puntos,progreso}=data;
  const activas=misiones.filter(m => m.activa);
  const recientes=[...progreso].sort((a,b) => b.fechaHora-a.fechaHora).slice(0,4);
  const ranking=[...usuarios].sort(byPoints).slice(0,3);
  const days=Array.from({length:7},(_,i) => { const d=new Date(); d.setDate(d.getDate()-6+i); d.setHours(0,0,0,0); const n=progreso.filter(p => p.fechaHora>=d.getTime() && p.fechaHora<d.getTime()+86400000).length; return {label:new Intl.DateTimeFormat('es',{weekday:'short'}).format(d),count:n,date:d.toLocaleDateString('es')}; });
  const max=Math.max(1,...days.map(d => d.count));
  return <>
    <section className="hero-banner"><div><span className="hero-label"><Compass size={15}/> CAMPUS QUEST · ADMIN</span><h2>Un campus para descubrir.<br/>Una comunidad para crecer.</h2><p>Gestiona las misiones y conecta a cada estudiante<br className="desktop-break"/> con los lugares que hacen especial tu universidad.</p><button className="hero-link" onClick={() => go('points')}>Explorar el campus <ArrowRight size={17}/></button></div><div className="hero-graphic" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="graphic-target"><Compass size={58}/></span><span className="floating-badge floating-one"><MapPin size={22}/></span><span className="floating-badge floating-two"><Award size={24}/></span><span className="sparkle-one">✦</span><span className="sparkle-two">✧</span></div></section>
    <section className="stats-grid"><Stat icon={Users} label="Usuarios" value={usuarios.length} detail="Cuentas registradas en el campus"/><Stat icon={Target} label="Misiones activas" value={activas.length} detail="Aventuras listas para descubrir"/><Stat icon={MapPin} label="Puntos del campus" value={puntos.length} detail="Lugares que conectan"/><Stat icon={Award} label="Misiones completadas" value={progreso.length} detail="Cada logro, una nueva insignia"/></section>
    <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h2>Así se mueve tu campus</h2><p>Misiones completadas · Últimos 7 días</p></div><span className="chart-total"><TrendingUp size={15}/>{days.reduce((s,d) => s+d.count,0)} logros</span></div><div className="bar-chart" role="img" aria-label={days.map(d => `${d.date}: ${d.count} misiones`).join('; ')}>{days.map((d,i) => <div className="bar-column" key={d.date}><span className="bar-value">{d.count}</span><div className="bar-track"><div className={`bar-fill ${i===6 ? 'bar-today' : ''}`} style={{height:`${d.count/max*100}%`}}/></div><span>{d.label}</span></div>)}</div></section><section className="panel campus-panel"><div className="panel-heading"><div><h2>Tu campus, conectado</h2><p>{puntos.length} destinos. Infinitas historias.</p></div><MapPin size={18}/></div><div className="campus-preview"><img src="/campus-map.jpg" alt="Mapa ilustrado del campus de ULEAM compartido con Android"/><span className="map-caption"><span className="live-dot"/> Mapa del campus</span></div><button className="campus-link" onClick={() => go('points')}>Ver puntos de interés <ArrowRight size={16}/></button></section></div>
    <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h2>Misiones por descubrir</h2><p>El primer paso de una gran aventura</p></div><button className="text-button" onClick={() => go('missions')}>Ver todas <ArrowRight size={15}/></button></div>{activas.slice(0,4).map(m => <div className="mission-row" key={m.id}><span className="mission-emoji">{m.insigniaEmoji}</span><div><strong>{m.titulo}</strong><small>{puntos.find(p => p.id===m.puntoInteresId)?.nombre || 'Punto no disponible'}</small></div><span className="points-label">+{m.puntos} <small>XP</small></span><span className="status-badge">Activa</span></div>)}{!activas.length && <Empty title="Tu primera misión te espera" text="Crea una misión para comenzar la aventura."/>}</section><section className="panel"><div className="panel-heading"><div><h2>Exploradores destacados</h2><p>La constancia merece su reconocimiento</p></div><button className="text-button" onClick={() => go('users')}>Ver todos <ArrowRight size={15}/></button></div>{ranking.map((u,i) => <button className="ranking-row" key={u.id} onClick={() => onUser(u)}><span className="rank-number">0{i+1}</span><span className="avatar">{initials(u.nombres)}</span><span className="ranking-name"><strong>{u.nombres}</strong><small>Nivel {u.nivel} · {u.rol}</small></span><span className="points-label">{u.puntajeAcumulado}<small> XP</small></span></button>)}{!ranking.length && <Empty title="Sin exploradores todavía" text="Los usuarios aparecerán cuando se registren en el servidor."/>}<div className="ranking-note"><Award size={15}/> Pequeños pasos. Grandes descubrimientos.</div></section></div>
    <section className="panel"><div className="panel-heading"><div><h2>Las últimas aventuras</h2><p>Historias que suceden en tu campus</p></div><button className="text-button" onClick={() => go('reports')}>Ver actividad <ArrowRight size={15}/></button></div><div className="recent-grid">{recientes.map(p => { const u=usuarios.find(u => u.id===p.usuarioId); const m=misiones.find(m => m.id===p.misionId); return <button key={p.id} className="recent-item" onClick={() => u && onUser(u)}><span className="mission-emoji">{m?.insigniaEmoji || '🏅'}</span><span><strong>{u?.nombres || `Usuario #${p.usuarioId}`}</strong><small>{m?.titulo || `Misión #${p.misionId}`}</small><time>{formatDate(p.fechaHora)}</time></span></button>; })}</div>{!recientes.length && <Empty title="El inicio de una aventura" text="Aquí verás las misiones completadas por tus estudiantes."/>}</section>
  </>;
}
