import { useState } from 'react';
import { Clock, Copy, MapPin, Pencil, QrCode, Target } from 'lucide-react';
import { Badge, Empty, Field, FormError, Modal, SearchBox } from '../components/common.jsx';
import { matches } from '../services/utils.js';

export default function Points({data,onEdit,notify}) {
  const [selected,setSelected]=useState(data.puntos[0]?.id); const [search,setSearch]=useState(''); const [category,setCategory]=useState('');
  const filtered=data.puntos.filter(p => (!category || p.categoria===category) && matches(`${p.nombre} ${p.codigoQr}`,search));
  const point=data.puntos.find(p => p.id===selected);
  async function copy(code) { try { await navigator.clipboard.writeText(code); notify('Código QR copiado.'); } catch { notify('No se pudo copiar. Selecciona el código y cópialo manualmente.'); } }
  return <><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Buscar un lugar o código QR"/><select aria-label="Categoría del punto" value={category} onChange={e => setCategory(e.target.value)}><option value="">Todas las categorías</option>{['Académico','Trámites','Servicios','Recreación'].map(c => <option key={c}>{c}</option>)}</select></div><div className="points-layout"><section className="panel full-map-panel"><div className="panel-heading"><div><h2>Descubre cada rincón</h2><p>Selecciona un marcador para ver el lugar</p></div><Badge>{data.puntos.length} puntos</Badge></div><div className="campus-map"><img src="/campus-map.jpg" alt="Plano ilustrado del campus de ULEAM"/>{data.puntos.map(p => <button key={p.id} className={`map-marker ${p.id===selected ? 'marker-selected' : ''}`} style={{left:`${p.posX*100}%`,top:`${p.posY*100}%`}} aria-label={`Ver ${p.nombre}`} aria-pressed={p.id===selected} title={p.nombre} onClick={() => setSelected(p.id)}><MapPin size={15}/><span>{p.id}</span></button>)}</div><p className="map-note">Las posiciones corresponden al plano de la app Android.</p></section><div className="points-column">{point && <section className="panel selected-point"><div className="panel-heading"><div><p className="eyebrow">LUGAR SELECCIONADO</p><h2>{point.nombre}</h2></div><button className="icon-button" aria-label={`Editar ${point.nombre}`} onClick={() => onEdit(point)}><Pencil size={17}/></button></div><Badge>{point.categoria}</Badge><p>{point.descripcion}</p><div className="point-detail"><Clock size={16}/><span>{point.horarioAtencion}</span></div><div className="point-detail"><Target size={16}/><span>{point.tramites}</span></div><div className="qr-code"><QrCode size={21}/><code>{point.codigoQr}</code><button className="icon-button" aria-label="Copiar código QR" onClick={() => copy(point.codigoQr)}><Copy size={16}/></button></div><small className="muted-copy">{data.misiones.filter(m => m.puntoInteresId===point.id && m.activa).length} misiones activas en este lugar</small></section>}<section className="panel"><div className="panel-heading"><div><h2>Lugares del campus</h2><p>{filtered.length} puntos en esta vista</p></div></div><div className="point-list">{filtered.map(p => <button key={p.id} onClick={() => setSelected(p.id)} className={`point-list-item ${p.id===selected ? 'point-selected' : ''}`}><span className="point-number">{p.id}</span><span><strong>{p.nombre}</strong><small>{p.categoria}</small></span><MapPin size={15}/></button>)}</div>{!filtered.length && <Empty/>}</section></div></div></>;
}

export function PointForm({point,onSave,onClose}) {
  const [form,setForm]=useState(point || {nombre:'',categoria:'Académico',descripcion:'',horarioAtencion:'',tramites:'',posX:0.5,posY:0.5,codigoQr:''});
  const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const set=(key,value) => setForm(f => ({...f,[key]:value}));
  async function submit(e) { e.preventDefault(); setSaving(true); setError(''); try { const next={...form,posX:Number(form.posX),posY:Number(form.posY)}; for (const key of ['nombre','descripcion','horarioAtencion','tramites','codigoQr']) next[key]=next[key].trim(); next.codigoQr=next.codigoQr.toUpperCase(); await onSave(next); } catch(e) { setError(e.message); setSaving(false); } }
  return <Modal title={point ? 'Editar punto del campus' : 'Agregar un punto del campus'} onClose={onClose} locked={saving} wide><form onSubmit={submit}><div className="form-grid"><Field label="Nombre del lugar"><input required minLength={2} maxLength={160} value={form.nombre} onChange={e => set('nombre',e.target.value)}/></Field><Field label="Categoría"><select value={form.categoria} onChange={e => set('categoria',e.target.value)}>{['Académico','Trámites','Servicios','Recreación'].map(c => <option key={c}>{c}</option>)}</select></Field><div className="field-full"><Field label="Descripción"><textarea required rows={2} maxLength={2000} value={form.descripcion} onChange={e => set('descripcion',e.target.value)}/></Field></div><Field label="Horario de atención"><input required maxLength={300} value={form.horarioAtencion} onChange={e => set('horarioAtencion',e.target.value)} placeholder="Lunes a viernes, 08:00 a 17:00"/></Field><Field label="Servicios y trámites"><input required maxLength={1000} value={form.tramites} onChange={e => set('tramites',e.target.value)}/></Field><Field label="Posición horizontal (0 a 1)" hint="0 es el borde izquierdo; 1 es el derecho."><input type="number" min={0} max={1} step="any" required value={form.posX} onChange={e => set('posX',e.target.value)}/></Field><Field label="Posición vertical (0 a 1)" hint="0 es el borde superior; 1 es el inferior."><input type="number" min={0} max={1} step="any" required value={form.posY} onChange={e => set('posY',e.target.value)}/></Field><div className="field-full"><Field label="Código QR único" hint="El texto que debe contener el QR del lugar."><input required minLength={3} maxLength={128} value={form.codigoQr} onChange={e => set('codigoQr',e.target.value)} placeholder="CQ-NUE-009"/></Field></div></div><FormError message={error}/><div className="modal-actions"><button type="button" className="secondary-button" disabled={saving} onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving}>{saving ? 'Guardando…' : 'Guardar punto'}</button></div></form></Modal>;
}
