import { useState } from 'react';
import { ArrowDownToLine, Award, Target, Users, Zap } from 'lucide-react';
import { Stat, Empty } from '../components/common.jsx';
import { downloadCsv, filterPeriod, formatDate } from '../services/utils.js';

export default function Reports({data}) {
  const [days,setDays]=useState(7);
  const progress=filterPeriod(data.progreso,days).sort((a,b) => b.fechaHora-a.fechaHora);
  const users=new Set(progress.map(p => p.usuarioId)).size;
  const participation=data.usuarios.length ? Math.round(users/data.usuarios.length*100) : 0;
  const points=progress.reduce((s,p) => s+p.puntosObtenidos,0);
  function exportReport() { downloadCsv('campus-quest-progreso.csv',['ID','Usuario','Misión','Lugar','Fecha','Puntos','Código QR'],progress.map(p => { const m=data.misiones.find(m => m.id===p.misionId); return [p.id,data.usuarios.find(u => u.id===p.usuarioId)?.nombres || p.usuarioId,m?.titulo || p.misionId,data.puntos.find(x => x.id===m?.puntoInteresId)?.nombre || '',new Date(p.fechaHora).toISOString(),p.puntosObtenidos,p.codigoQrValidado]; })); }
  return <><div className="toolbar"><div className="period-tabs" role="group" aria-label="Periodo del reporte">{[[7,'7 días'],[30,'30 días'],[0,'Todo el historial']].map(([n,label]) => <button key={n} className={days===n ? 'selected' : ''} aria-pressed={days===n} onClick={() => setDays(n)}>{label}</button>)}</div><button className="secondary-button" onClick={exportReport}><ArrowDownToLine size={15}/>Exportar CSV</button></div><section className="stats-grid"><Stat icon={Target} label="Misiones completadas" value={progress.length} detail="Durante el periodo seleccionado"/><Stat icon={Users} label="Exploradores activos" value={users} detail="Con al menos una misión completada"/><Stat icon={Zap} label="Puntos obtenidos" value={points} detail="Recompensas registradas"/><Stat icon={Award} label="Participación" value={`${participation}%`} detail="Exploradores activos / total de usuarios"/></section><section className="panel"><div className="panel-heading"><div><h2>Bitácora de exploración</h2><p>El historial conserva también las misiones archivadas.</p></div></div><div className="table-scroll"><table><thead><tr><th>Explorador</th><th>Misión</th><th>Lugar</th><th>Fecha</th><th>Puntos</th></tr></thead><tbody>{progress.map(p => { const m=data.misiones.find(m => m.id===p.misionId); return <tr key={p.id}><td>{data.usuarios.find(u => u.id===p.usuarioId)?.nombres || `Usuario #${p.usuarioId}`}</td><td><strong>{m?.titulo || `Misión #${p.misionId}`}</strong>{m && !m.activa && <small>Archivada</small>}</td><td>{data.puntos.find(x => x.id===m?.puntoInteresId)?.nombre || '—'}</td><td className="nowrap">{formatDate(p.fechaHora)}</td><td><span className="points-label">+{p.puntosObtenidos} XP</span></td></tr>; })}</tbody></table></div>{!progress.length && <Empty title="Sin actividad en este periodo" text="Selecciona un periodo más amplio para consultar el historial."/>}<p className="result-count">{progress.length} registros · Las fechas se muestran en la zona horaria de tu dispositivo.</p></section></>;
}
