import { useState } from 'react';
import { ArrowDownToLine, ArrowRight, Award, Target, Zap } from 'lucide-react';
import { Badge, Empty, Modal, SearchBox } from '../components/common.jsx';
import { initials, byPoints, matches, downloadCsv, formatDate } from '../services/utils.js';

export default function Users({data,onUser}) {
  const [search,setSearch]=useState(''); const [role,setRole]=useState('');
  const filtered=[...data.usuarios].sort(byPoints).filter(u => (!role || u.rol===role) && matches(`${u.nombres} ${u.correoInstitucional} ${u.carrera}`,search));
  function exportUsers() { downloadCsv('campus-quest-usuarios.csv',['ID','Nombre','Correo','Carrera','Rol','Nivel','Puntos'],filtered.map(u => [u.id,u.nombres,u.correoInstitucional,u.carrera,u.rol,u.nivel,u.puntajeAcumulado])); }
  return <section className="panel"><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Buscar por nombre, correo o carrera"/><div className="toolbar-actions"><select aria-label="Filtrar usuarios por rol" value={role} onChange={e => setRole(e.target.value)}><option value="">Todos los roles</option>{[...new Set(data.usuarios.map(u => u.rol))].map(r => <option key={r} value={r}>{r}</option>)}</select><button className="secondary-button" onClick={exportUsers}><ArrowDownToLine size={15}/>Exportar</button></div></div><div className="table-scroll"><table><thead><tr><th>Explorador</th><th>Carrera</th><th>Rol</th><th>Nivel</th><th>Puntos</th><th><span className="sr-only">Perfil</span></th></tr></thead><tbody>{filtered.map(u => <tr key={u.id}><td><button className="user-cell" onClick={() => onUser(u)}><span className="avatar">{initials(u.nombres)}</span><span><strong>{u.nombres}</strong><small>{u.correoInstitucional || 'Visitante sin correo'}</small></span></button></td><td>{u.carrera}</td><td><Badge tone={u.rol==='visitante' ? 'amber' : ''}>{u.rol}</Badge></td><td><span className="level-chip">LV {u.nivel}</span></td><td><strong className="points-label">{u.puntajeAcumulado} XP</strong></td><td><button className="icon-button" aria-label={`Ver perfil de ${u.nombres}`} onClick={() => onUser(u)}><ArrowRight size={17}/></button></td></tr>)}</tbody></table></div>{!filtered.length && <Empty/>}<p className="result-count">{filtered.length} de {data.usuarios.length} usuarios · Ordenados por puntos acumulados</p></section>;
}

export function UserProfile({user,data,onClose}) {
  const history=data.progreso.filter(p => p.usuarioId===user.id).sort((a,b) => b.fechaHora-a.fechaHora);
  const nextLevel=100-user.puntajeAcumulado%100;
  return <Modal title="Perfil del explorador" onClose={onClose} wide><div className="profile-summary"><span className="avatar avatar-large">{initials(user.nombres)}</span><div><h3>{user.nombres}</h3><p>{user.correoInstitucional || 'Visitante del campus'}</p><p>{user.carrera}</p><Badge>{user.rol}</Badge></div></div><div className="profile-metrics"><div><Zap size={18}/><strong>{user.puntajeAcumulado}</strong><span>Puntos acumulados</span></div><div><Target size={18}/><strong>{history.length}</strong><span>Misiones completadas</span></div><div><Award size={18}/><strong>{user.nivel}</strong><span>Nivel actual</span></div></div><div className="level-progress"><div><strong>Próximo nivel</strong><small>Faltan {nextLevel} XP para el nivel {user.nivel+1}</small></div><progress value={user.puntajeAcumulado%100} max="100" aria-label="Progreso al siguiente nivel"/></div><h3 className="section-title">Insignias obtenidas</h3><div className="profile-badges">{history.map(p => { const m=data.misiones.find(m => m.id===p.misionId); return <div key={p.id} title={m?.insigniaNombre}><span>{m?.insigniaEmoji || '🏅'}</span><small>{m?.insigniaNombre || 'Insignia'}</small></div>; })}</div>{!history.length && <p className="muted-copy">Su primera insignia está esperando.</p>}<h3 className="section-title">Historial de misiones</h3><div className="profile-history">{history.map(p => { const m=data.misiones.find(m => m.id===p.misionId); const point=data.puntos.find(x => x.id===m?.puntoInteresId); return <div className="history-item" key={p.id}><span className="history-dot"/><div><strong>{m?.titulo || `Misión #${p.misionId}`}</strong><small>{point?.nombre || 'Punto del campus'}{m && !m.activa ? ' · Misión archivada' : ''}</small><time>{formatDate(p.fechaHora)}</time></div><span className="points-label">+{p.puntosObtenidos} XP</span></div>; })}</div>{!history.length && <Empty title="Una historia por comenzar" text="El progreso se registra al completar misiones en la app móvil."/>}</Modal>;
}
